### ISSUE TITLE
训练脚本报错，求助。。

### ISSUE THREAD

**Issue by 1343464520** [ChrisDud0257/SSL#2]
运行训练脚本报错：
(yolov8) PS D:\SR_Code\SSL-main\GAN-Based-SR> python D:\SR_Code\SSL-main\GAN-Based-SR\basicsr\train.py -opt D:\SR_Code\SSL-main\GAN-Based-SR/options/train/LDLSSL/train_LDLSSL_x2.yml --auto_resume
Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu118 as PyTorch extensions root...
D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu118\compute_similarity\build.ninja...
信息: 用提供的模式无法找到文件。
Traceback (most recent call last):
  File "D:\SR_Code\SSL-main\GAN-Based-SR\basicsr\train.py", line 11, in <module>
    from basicsr.data import build_dataloader, build_dataset
  File "d:\sr_code\ssl-main\gan-based-sr\basicsr\__init__.py", line 5, in <module>
    from .losses import *
  File "d:\sr_code\ssl-main\gan-based-sr\basicsr\losses\__init__.py", line 16, in <module>
    _model_modules = [importlib.import_module(f'basicsr.losses.{file_name}') for file_name in loss_filenames]
  File "d:\sr_code\ssl-main\gan-based-sr\basicsr\losses\__init__.py", line 16, in <listcomp>
    _model_modules = [importlib.import_module(f'basicsr.losses.{file_name}') for file_name in loss_filenames]
  File "D:\software\anaconda\envs\yolov8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "d:\sr_code\ssl-main\gan-based-sr\basicsr\losses\basic_loss.py", line 8, in <module>
    from .loss_util import weighted_loss
  File "d:\sr_code\ssl-main\gan-based-sr\basicsr\losses\loss_util.py", line 9, in <module>
    from basicsr.losses.similarity.similaritywrapper import compute_similarity
  File "d:\sr_code\ssl-main\gan-based-sr\basicsr\losses\similarity\similaritywrapper.py", line 15, in <module>
    SIMWrapper = load(name="compute_similarity",
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py", line 2238, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "D:\software\anaconda\envs\yolov8\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\software\anaconda\envs\yolov8\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
(yolov8) PS D:\SR_Code\SSL-main\GAN-Based-SR> nvcc -version
nvcc fatal   : Unknown option '-version'
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "D:\software\anaconda\envs\yolov8\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\software\anaconda\envs\yolov8\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

(yolov8) PS D:\SR_Code\SSL-main\GAN-Based-SR> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:40:05_Pacific_Daylight_Time_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0

请问：cuda版本是否不能高于11.7啊？我用的是之前的装好的cuda，如果用该项目是否得重新安装cuda了？

**Comment by 1343464520** [comment]
我pytorch版本是2.1的，是否要降到1.13跟给定版本一致？@ChrisDud0257

**Comment by ChrisDud0257** [comment]
> 我pytorch版本是2.1的，是否要降到1.13跟给定版本一致？@ChrisDud0257

看这个报错的话，可能报错不止和PyTorch有关，首先最好新创建一个conda环境，PyTorch安装1.13版本的，2.0+版本和我们的代码确实不兼容；第二点，你的CUDA可能有点问题，原因大概率是安装位置不对/没有正确导入到环境中/没有编译这个框架，但是11.8我们试过，是可以正确运行我们写好的CUDA算子的，这个应该没问题，这个框架是基于BasicsrSR编写的，有一些安装步骤你得走一下流程，你的报错貌似就像是没有编译成功这个框架，具体的编译过程我们在README的说明里面已经写了，请参照完成

**Comment by 1343464520** [comment]
> > 我pytorch版本是2.1的，是否要降到1.13跟给定版本一致？@ChrisDud0257
> 
> 看这个报错的话，可能报错不止和PyTorch有关，首先最好新创建一个conda环境，PyTorch安装1.13版本的，2.0+版本和我们的代码确实不兼容；第二点，你的CUDA可能有点问题，原因大概率是安装位置不对/没有正确导入到环境中/没有编译这个框架，但是11.8我们试过，是可以正确运行我们写好的CUDA算子的，这个应该没问题，这个框架是基于BasicsrSR编写的，有一些安装步骤你得走一下流程，你的报错貌似就像是没有编译成功这个框架，具体的编译过程我们在README的说明里面已经写了，请参照完成

多谢您的快速回复。我先按照readme要求重新创建环境配置来，看看是否正常。

**Comment by 1343464520** [comment]
@ChrisDud0257 现在可以跑起来了，但从打印log来看，似乎还是有一些问题：
ninja: no work to do.
Loading extension module compute_similarity...
Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja...
Building extension module compute_similarity_backward...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module compute_similarity_backward...
Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity\build.ninja...
Building extension module compute_similarity...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module compute_similarity...
Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja...
Building extension module compute_similarity_backward...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module compute_similarity_backward...
2024-09-27 10:52:31,898 INFO: [LDLSS..][epoch:  2, iter:   2,000, lr:(1.000e-04,)] [eta: 20:32:44, time (data): 0.346 (0.099)] l_pix: 1.2439e-04 l_selfsim: 2.9502e-01 l_selfsim_kl: 8.1711e-02 l_g_artifacts: 2.5232e-05 l_g_percep: 3.7830e+00 l_g_gan: 6.0008e-02 l_d_real: 7.5957e-06 l_d_fake: 6.8507e-06 out_d_real: -3.0943e+01 out_d_fake: -4.2945e+01
2024-09-27 10:52:31,899 INFO: Saving models and training states.
D:\software\anaconda\envs\ssl-gan\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\software\anaconda\envs\ssl-gan\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to C:\Users\13434/.cache\torch\hub\checkpoints\alexnet-owt-7be5be79.pth
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 164M/233M [01:07<00:28, 2.49MB/s]

**Comment by ChrisDud0257** [comment]
> @ChrisDud0257 现在可以跑起来了，但从打印log来看，似乎还是有一些问题： ninja: no work to do. Loading extension module compute_similarity... Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja... Building extension module compute_similarity_backward... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module compute_similarity_backward... Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity\build.ninja... Building extension module compute_similarity... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module compute_similarity... Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja... Building extension module compute_similarity_backward... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module compute_similarity_backward... 2024-09-27 10:52:31,898 INFO: [LDLSS..][epoch: 2, iter: 2,000, lr:(1.000e-04,)] [eta: 20:32:44, time (data): 0.346 (0.099)] l_pix: 1.2439e-04 l_selfsim: 2.9502e-01 l_selfsim_kl: 8.1711e-02 l_g_artifacts: 2.5232e-05 l_g_percep: 3.7830e+00 l_g_gan: 6.0008e-02 l_d_real: 7.5957e-06 l_d_fake: 6.8507e-06 out_d_real: -3.0943e+01 out_d_fake: -4.2945e+01 2024-09-27 10:52:31,899 INFO: Saving models and training states. D:\software\anaconda\envs\ssl-gan\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead. warnings.warn( D:\software\anaconda\envs\ssl-gan\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to C:\Users\13434/.cache\torch\hub\checkpoints\alexnet-owt-7be5be79.pth 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 164M/233M [01:07<00:28, 2.49MB/s]

请你先仔细看下报错的原因是什么，想想是不是其他原因(而非这个项目的bug)再来提问。你仔细看你的log，明显现在是能训练的，第2000个iteration的日志都能输出出来，但是你这个问题一看就是在训练过程的验证阶段中，计算LPIPS的时候，AlexNet下载不下来，因为你的网络被屏蔽了，下载AlexNet得能连得上外网才能解决，这个网络问题和我们的代码没任何关系。你问我，我也没办法帮你解决，这种问题你百度一下就知道了

**Comment by ChrisDud0257** [comment]
> @ChrisDud0257 现在可以跑起来了，但从打印log来看，似乎还是有一些问题： ninja: no work to do. Loading extension module compute_similarity... Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja... Building extension module compute_similarity_backward... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module compute_similarity_backward... Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity\build.ninja... Building extension module compute_similarity... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module compute_similarity... Using C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja... Building extension module compute_similarity_backward... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module compute_similarity_backward... 2024-09-27 10:52:31,898 INFO: [LDLSS..][epoch: 2, iter: 2,000, lr:(1.000e-04,)] [eta: 20:32:44, time (data): 0.346 (0.099)] l_pix: 1.2439e-04 l_selfsim: 2.9502e-01 l_selfsim_kl: 8.1711e-02 l_g_artifacts: 2.5232e-05 l_g_percep: 3.7830e+00 l_g_gan: 6.0008e-02 l_d_real: 7.5957e-06 l_d_fake: 6.8507e-06 out_d_real: -3.0943e+01 out_d_fake: -4.2945e+01 2024-09-27 10:52:31,899 INFO: Saving models and training states. D:\software\anaconda\envs\ssl-gan\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead. warnings.warn( D:\software\anaconda\envs\ssl-gan\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to C:\Users\13434/.cache\torch\hub\checkpoints\alexnet-owt-7be5be79.pth 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 164M/233M [01:07<00:28, 2.49MB/s]

好像还不对，我仔细看了一眼，你这个不是下载速度2.49M/S吗？能下载下来啊，那这里有报错吗？我没看见任何的Error，那你的问题是什么呢？你说的不对是指什么地方呢？

**Comment by 1343464520** [comment]
我没说你的代码有报错。。只是打印了一些跟cuda相关的依赖，怀疑编译是不是还存在问题:
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja...
Building extension module compute_similarity_backward...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do. 
模型都正常下载好的，目前在尝试你的LDL+SSL脚本train的，我是跑了LDL算法后觉得还不错，看看你的算法改进效果相比LDL在我的数据集上是否也有更好的改进。如果这个打印日志没啥毛病，就这样给它跑吧hh

**Comment by ChrisDud0257** [comment]
> 我没说你的代码有报错。。只是打印了一些跟cuda相关的依赖，怀疑编译是不是还存在问题: Detected CUDA files, patching ldflags Emitting ninja build file C:\Users\13434\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\compute_similarity_backward\build.ninja... Building extension module compute_similarity_backward... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. 模型都正常下载好的，目前在尝试你的LDL+SSL脚本train的，我是跑了LDL算法后觉得还不错，看看你的算法改进效果相比LDL在我的数据集上是否也有更好的改进。如果这个打印日志没啥毛病，就这样给它跑吧hh

没有Error抛出导致程序停掉就是正常的，这些都是CUDA运行阶段编译的正常输出
